/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edunova.view;

import edunova.controller.ObradaGrupa;
import edunova.controller.ObradaPredavac;
import edunova.controller.ObradaSmjer;
import edunova.model.Grupa;
import edunova.model.Predavac;
import edunova.model.Smjer;
import edunova.pomocno.EdunovaException;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Date;
import java.util.Locale;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Profesor
 */
public class Grupe extends javax.swing.JFrame {

    private final ObradaGrupa obradaEntitet;
    private static DefaultComboBoxModel<Smjer> modelSmjer;
    private static DefaultComboBoxModel<Predavac> modelPredavac;

    /**
     * Creates new form Grupe
     */
    public Grupe() {
        initComponents();
        obradaEntitet = new ObradaGrupa();

        DefaultComboBoxModel<Smjer> ms = new DefaultComboBoxModel<>();
        Smjer sm = new Smjer();
        sm.setSifra(0);
        sm.setNaziv("Odaberite smjer");
        ms.addElement(sm);
        new ObradaSmjer().getLista().forEach((s) -> {
            ms.addElement(s);
        });
        cmbSmjerovi.setModel(ms);
        
        
        
        DefaultComboBoxModel<Predavac> mp = new DefaultComboBoxModel<>();
        Predavac pm = new Predavac();
        pm.setSifra(0);
        pm.setIme("Odaberite");
        pm.setPrezime("predavača");
        mp.addElement(pm);
        new ObradaPredavac().getLista().forEach((p) -> {
            mp.addElement(p);
        });
        cmbPredavaci.setModel(mp);
        
        dpDatumPocetka.setLocale(new Locale("hr","HR"));
        dpDatumPocetka.getSettings().setTranslationToday("Danas");
        dpDatumPocetka.getSettings().setTranslationClear("Poništi");
        dpDatumPocetka.getSettings().setFormatForDatesCommonEra("dd. MMMM yyyy.");
        dpDatumPocetka.getSettings().setFormatForDatesBeforeCommonEra("dd. MMMM uuuu.");

        ucitajPodatke();

    }

    private void ucitajPodatke() {
        DefaultListModel<Grupa> m = new DefaultListModel<>();
        obradaEntitet.getLista().forEach((g) -> {
            m.addElement(g);
        });
        lstEntiteti.setModel(m);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lstEntiteti = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        txtNaziv = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cmbSmjerovi = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cmbPredavaci = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        dpDatumPocetka = new com.github.lgooddatepicker.components.DatePicker();
        bntDodaj = new javax.swing.JButton();
        bntPromjeni = new javax.swing.JButton();
        bntObrisi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lstEntiteti.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstEntitetiValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstEntiteti);

        jLabel1.setText("Naziv");

        jLabel2.setText("Smjer");

        jLabel3.setText("Predavač");

        jLabel4.setText("Datum početka");

        bntDodaj.setText("Dodaj");
        bntDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntDodajActionPerformed(evt);
            }
        });

        bntPromjeni.setText("Promjeni");

        bntObrisi.setText("Obriši");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbPredavaci, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dpDatumPocetka, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtNaziv)
                    .addComponent(cmbSmjerovi, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bntDodaj)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bntPromjeni)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bntObrisi)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(526, 526, 526))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bntDodaj)
                    .addComponent(bntPromjeni)
                    .addComponent(bntObrisi))
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbSmjerovi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbPredavaci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(dpDatumPocetka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lstEntitetiValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstEntitetiValueChanged
       if(evt.getValueIsAdjusting()){
           return;
       }
       
       ocistiPolja();
       
       Grupa g = lstEntiteti.getSelectedValue();
       
       if(g==null){
           return;
       }
       
       txtNaziv.setText(g.getNaziv());
        //System.out.println(g.getDatumPocetka().getClass().getName());
        if(g.getDatumPocetka()!=null){
             Date dt = new Date(g.getDatumPocetka().getTime());
             LocalDate d = dt.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
             dpDatumPocetka.setDate(d);
        }
       
       //1. način
       //cmbSmjerovi.setSelectedItem(g.getSmjer());
       
       //2. način
       modelSmjer  = (DefaultComboBoxModel<Smjer>)cmbSmjerovi.getModel();
       for(int i=0;i<modelSmjer.getSize();i++){
           if(modelSmjer.getElementAt(i).getSifra()==g.getSmjer().getSifra()){
               cmbSmjerovi.setSelectedIndex(i);
               break;
           }
       }
       
       modelPredavac  = (DefaultComboBoxModel<Predavac>)cmbPredavaci.getModel();
       for(int i=0;i<modelPredavac.getSize();i++){
           if(modelPredavac.getElementAt(i).getSifra()==g.getPredavac().getSifra()){
               cmbPredavaci.setSelectedIndex(i);
               break;
           }
       }
       
       
    }//GEN-LAST:event_lstEntitetiValueChanged

    private void ocistiPolja(){
        txtNaziv.setText("");
        cmbSmjerovi.setSelectedIndex(0);
        cmbPredavaci.setSelectedIndex(0);
        dpDatumPocetka.setDate(null);
    }
    private void bntDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntDodajActionPerformed
        
        Grupa g = new Grupa();
        g.setNaziv(txtNaziv.getText());
        g.setSmjer((Smjer)cmbSmjerovi.getSelectedItem());
        g.setPredavac((Predavac)cmbPredavaci.getSelectedItem());
        try {
            Date date = Date.from(dpDatumPocetka.getDate().atStartOfDay(ZoneId.systemDefault()).toInstant());
            g.setDatumPocetka(date);
        } catch (Exception e) {
            g.setDatumPocetka(null);
        }
        
        
        try {
            obradaEntitet.spremi(g);
            ocistiPolja();
            ucitajPodatke();
        } catch (EdunovaException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        
        
    }//GEN-LAST:event_bntDodajActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntDodaj;
    private javax.swing.JButton bntObrisi;
    private javax.swing.JButton bntPromjeni;
    private javax.swing.JComboBox<Predavac> cmbPredavaci;
    private javax.swing.JComboBox<Smjer> cmbSmjerovi;
    private com.github.lgooddatepicker.components.DatePicker dpDatumPocetka;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<Grupa> lstEntiteti;
    private javax.swing.JTextField txtNaziv;
    // End of variables declaration//GEN-END:variables

}
