/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edunova;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Profesor
 */
public class Prozor extends javax.swing.JFrame {

    /**
     * Creates new form Prozor
     */
    public Prozor() {
        initComponents();
        //mi svoje izmjene uvijek pišemo nakon initComponents
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        poruka = new javax.swing.JLabel();
        gumb = new javax.swing.JButton();
        definirajGrad = new javax.swing.JButton();
        ocisti = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 204));

        poruka.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        poruka.setText("Edunova");

        gumb.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        gumb.setText("Pozdravi");
        gumb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gumbActionPerformed(evt);
            }
        });

        definirajGrad.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        definirajGrad.setText("Definiraj grad");
        definirajGrad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                definirajGradActionPerformed(evt);
            }
        });

        ocisti.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ocisti.setText("Očisti");
        ocisti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ocistiActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        jMenuItem1.setText("About");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Izlaz");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(gumb)
                .addGap(31, 31, 31)
                .addComponent(definirajGrad, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ocisti, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(poruka, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(111, 111, 111))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(poruka)
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(gumb)
                    .addComponent(definirajGrad)
                    .addComponent(ocisti))
                .addContainerGap(183, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gumbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gumbActionPerformed
       poruka.setText("Hello");
    }//GEN-LAST:event_gumbActionPerformed

    private void definirajGradActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_definirajGradActionPerformed
        poruka.setText(JOptionPane.showInputDialog("Unesi ime grada"));
    }//GEN-LAST:event_definirajGradActionPerformed

    private void ocistiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ocistiActionPerformed
        poruka.setText("");
    }//GEN-LAST:event_ocistiActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        new About().setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    public void ispis(){
        
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton definirajGrad;
    private javax.swing.JButton gumb;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JButton ocisti;
    private javax.swing.JLabel poruka;
    // End of variables declaration//GEN-END:variables
}
