/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edunova;

import java.awt.Color;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;
import javax.swing.DefaultListModel;

/**
 *
 * @author Profesor
 */
public class Prozor extends javax.swing.JFrame {

    private Color pocetna;
    /**
     * Creates new form Prozor
     */
    public Prozor() {
        initComponents();
        pocetna=btnBoja.getBackground();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtPB = new javax.swing.JTextField();
        txtDB = new javax.swing.JTextField();
        btnZbroji = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstBrojevi = new javax.swing.JList<>();
        btnBoja = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnZbroji.setText("jButton1");
        btnZbroji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZbrojiActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(lstBrojevi);

        btnBoja.setText("jButton1");
        btnBoja.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBojaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBojaMouseExited(evt);
            }
        });
        btnBoja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBojaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(txtPB, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(txtDB, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(btnZbroji)
                .addContainerGap(88, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBoja)
                .addGap(47, 47, 47))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnZbroji))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(btnBoja)))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnZbrojiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZbrojiActionPerformed
        try {
            int i = Integer.parseInt(txtPB.getText());
            int j = Integer.parseInt(txtDB.getText());
            System.out.println(i + j);
        } catch (Exception e) {
            System.out.println("Niste unijeli brojeve");
        }
        
        DefaultListModel<String> m = new DefaultListModel<>();
        
        for(int i=0;i<100;i++){
            m.addElement(String.valueOf(i+1));
        }
        
        lstBrojevi.setModel(m);
        
        
        int i=3,j=8,k=-2;
        
        List<Integer> lista = new ArrayList<>();
        
        lista.add(i);
        lista.add(j);
        lista.add(k);
        
        Collections.sort(lista);
        
        System.out.println(lista.get(lista.size()-1));
        
        
        

    }//GEN-LAST:event_btnZbrojiActionPerformed

    private void btnBojaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBojaMouseEntered
       btnBoja.setBackground(Color.GREEN);
    }//GEN-LAST:event_btnBojaMouseEntered

    private void btnBojaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBojaMouseExited
       btnBoja.setBackground(pocetna);
    }//GEN-LAST:event_btnBojaMouseExited

    private void btnBojaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBojaActionPerformed
        setTitle("Hello world");
    }//GEN-LAST:event_btnBojaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBoja;
    private javax.swing.JButton btnZbroji;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> lstBrojevi;
    private javax.swing.JTextField txtDB;
    private javax.swing.JTextField txtPB;
    // End of variables declaration//GEN-END:variables
}
